# Generated by Django 3.2.13 on 2022-07-28 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Full Name')),
                ('email_address', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Email')),
                ('ph_no', models.BigIntegerField(blank=True, null=True, verbose_name='Phone No')),
                ('delivery_address', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Device Delivery Address')),
                ('street_number', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Street No.')),
                ('route', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Route')),
                ('city', models.CharField(blank=True, max_length=2500, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2500, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Country')),
                ('address_verified', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Address Verified by Google?')),
                ('number_of_devices', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Number Of Devices')),
                ('amount', models.BigIntegerField(blank=True, null=True, verbose_name='Total Paid Amount')),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Order-Devices-Details',
            },
        ),
        migrations.CreateModel(
            name='Price_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('highlight_status', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Price Plan',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('subsciption_from', models.DateField(verbose_name='Subscription From')),
                ('subsciption_to', models.DateField(verbose_name='Subscription To')),
                ('status', models.CharField(default='Expire', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_methods.price_plan')),
                ('serial_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.devices', verbose_name='Serial No.')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Price_plan_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_methods.price_plan')),
            ],
            options={
                'verbose_name': 'Plan Features',
            },
        ),
    ]
