# Generated by Django 3.2.13 on 2023-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_plan',
            name='plan_choice',
            field=models.CharField(choices=[('device', 'Device'), ('certificate', 'Certificate')], default='device', max_length=255, unique=True),
        ),
    ]
