# Generated by Django 3.2.13 on 2022-07-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone No')),
                ('picture', models.ImageField(blank=True, upload_to='ProfileImages', verbose_name='Photo')),
                ('user_selected_timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Timezones')),
                ('user_register_at_his_timezones', models.CharField(blank=True, max_length=70, null=True, verbose_name='Register Timezones')),
                ('gender', models.CharField(blank=True, max_length=25, null=True, verbose_name='Gender')),
                ('profession', models.CharField(blank=True, max_length=25, null=True)),
                ('otp', models.CharField(blank=True, max_length=25, null=True, verbose_name='OTP')),
                ('address', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=2500, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2500, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Zip Code')),
                ('changed_default_password', models.CharField(blank=True, default='No', max_length=500, null=True, verbose_name='Changed Default Password?')),
                ('confirmation_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Compensation Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
