# Generated by Django 3.2.13 on 2023-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_device_data',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='api_device_data',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='api_device_data',
            name='mtbf',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='MTBF'),
        ),
        migrations.AddField(
            model_name='api_device_data',
            name='mttr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='MTTR'),
        ),
        migrations.AddField(
            model_name='api_device_data',
            name='stop',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='stop'),
        ),
    ]
