# Generated by Django 3.2.13 on 2023-04-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
