# Generated by Django 3.2.13 on 2023-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('api_code', models.CharField(max_length=255, unique=True)),
                ('api_secret', models.TextField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_auth', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
