# Generated by Django 3.2.13 on 2023-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20230502_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
