# Generated by Django 3.2.13 on 2023-05-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0003_invoice'),
        ('Home', '0008_devices_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='inv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_id', to='payment_methods.invoice'),
        ),
    ]
